# https://learn.microsoft.com/en-us/azure/ai-services/openai/reference
# https://platform.openai.com/tokenizer
# https://help.openai.com/en/articles/6654000-best-practices-for-prompt-engineering-with-openai-api
# Remember to create an .env file similar to the .env.example file with the actual values


POST {{$dotenv DAVINCI_OPENAI_FULL_ENDPOINT}} HTTP/1.1
api-key: {{$dotenv %DAVINCI_OPENAI_KEY}}
Content-Type: application/json

{
    "prompt": "What is the speed of light in kilometers per hour?",
    "max_tokens": 100,
    "temperature": 0.3
}

###

POST {{$dotenv GPT_OPENAI_FULL_ENDPOINT}} HTTP/1.1
api-key: {{$dotenv %GPT_OPENAI_KEY}}
Content-Type: application/json

{
    "messages": [
        {
            "role" : "system",
            "content" : "You are a general assistant."
        },
        {
            "role" : "user",
            "content" : "What is the speed of light in kilometers per hour?"
        }
    ],
    "max_tokens": 100,
    "temperature": 0.3,
    "n": 1
}

###
POST {{$dotenv GPT_OPENAI_FULL_ENDPOINT}} HTTP/1.1
api-key: {{$dotenv %GPT_OPENAI_KEY}}
Content-Type: application/json

{
    "messages": [
        {
            "role" : "user",
            "content" : "What is the disntance to the Moon?"
        }
    ],
    "max_tokens": 100,
    "temperature": 0.3,
    "n":1,
    "stream": true
}

###

POST {{$dotenv GPT_OPENAI_FULL_ENDPOINT}} HTTP/1.1
api-key: {{$dotenv %GPT_OPENAI_KEY}}
Content-Type: application/json

{
    "messages": [
        {
            "role" : "user",
            "content" : "Write a blog about Pakistan's history."
        }
    ],
    "max_tokens": 100,
    "temperature": 0.3
}
###

POST {{$dotenv GPT_OPENAI_FULL_ENDPOINT}} HTTP/1.1
api-key: {{$dotenv %GPT_OPENAI_KEY}}
Content-Type: application/json

{
    "messages": [
        {"role":"system","content":"You are a general assistant"},
        {"role":"user","content":"What is the speed of light?"}
    ],
    "max_tokens": 100,
    "temperature": 0.3
}

###

POST {{$dotenv ADA_OPENAI_FULL_ENDPOINT}} HTTP/1.1
api-key: {{$dotenv %ADA_OPENAI_KEY}}
Content-Type: application/json

{
    "input":"As your use of Azure OpenAI evolves, and you start to build and integrate with applications you will likely want to manually control model updates so that you can first test and validate that model performance is remaining consistent for your use case prior to upgrade.\nWhen you select a specific model version for a deployment this version will remain selected until you either choose to manually update yourself, or once you reach the retirement date for the model. When the retirement date is reached the model will auto-upgrade to the default version at the time of retirement."
}

###

POST {{$dotenv ADA_OPENAI_FULL_ENDPOINT}} HTTP/1.1
api-key: {{$dotenv %ADA_OPENAI_KEY}}
Content-Type: application/json

{
    "input":"Top restaruants in Miami are: \n1. Versalles\n2. Joes Stone Crab"
}

###

POST {{$dotenv GPT_OPENAI_FULL_ENDPOINT}} HTTP/1.1
api-key: {{$dotenv %GPT_OPENAI_KEY}}
Content-Type: application/json

{
    "messages": [
        {"role":"system","content":"You are a general assistant"},
        {"role":"user","content":"What are the top restaurants in Miami from this list:Top restaruants in Miami are: \n1. Versalles\n2. Joes Stone Crab"}
    ],
    "max_tokens": 100,
    "temperature": 0.3
}